### PR TITLE
Rc12 update.

### PR DESCRIPTION
**Pull request by boris-spas**

### CODE REVIEW

**Comment by boris-spas** [comment]
@rathrio We seem to have a problem on rc12. I've seen something similar to this and I think I know how to fix it. Let's discuss on Friday.

**Comment by rathrio** [comment]
@boris-spas Currently investigating why this is hanging for R. Let me know if you see something obvious.

**Comment by boris-spas** [comment]
There seem to be more changes that just the thread local. why?
edit: notably the commented out test.

**Comment by rathrio** [comment]
I DRYed some things up (e.g. the meta object lookup), but good point -> should probably test it in isolation.

I commented out the R test to see whether the build would pass without it.

**Pull request merged**
